### ISSUE TITLE
CDN Link - version 6.0.0 - 404

### ISSUE THREAD

**Issue by traue** [bootboxjs/bootbox#850] opened 2024-02-07 19:17 UTC
Hi

I tried using the CDN on the website:

https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/6.0.0/bootbox.all.min.js

Available here: https://bootboxjs.com/getting-started.html

But it is returning 404.

On the CDN the correct link is:

https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/6.0.0/bootbox.min.js

Just to inform.

Best wishes,

T.

**Comment by tiesont** [comment] 2024-02-08 20:26
Duplicate of #840 - we've requested an update, but it doesn't seem to be pulling in the .all version of the library.

`bootbox.min.js` and `bootbox.all.min.js` are _not_ the same file - the former only includes the English locale, whereas the latter includes all the locales found in `bootbox.locales.min.js`.

**Closed by tiesont** 2024-02-08 20:26 UTC
